// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: app/fairshare/command/command.proto

// app.fairshare.command：节点级拥塞门控（common/protocol/node_fairshare.go）的下发面。
// 所有参数由上层下发；0 一律是「没有这一项」，内核不藏默认值。

package command

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ⚠️ 单位：本文件里的速率一律是 **字节/秒**（avail_bps 是历史名字，也是字节/秒），
// 而 common/protocol/user.proto 里 User 的 `*_bps` 是 **比特/秒**。
type SetNodeBandwidthRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	AvailBps uint64                 `protobuf:"varint,1,opt,name=avail_bps,json=availBps,proto3" json:"avail_bps,omitempty"` // root_cap，字节/秒。0 = 关闭节点级调度。
	// 拥塞滞回（百分比/计数）。
	CongestionEnterPercent uint32 `protobuf:"varint,4,opt,name=congestion_enter_percent,json=congestionEnterPercent,proto3" json:"congestion_enter_percent,omitempty"` // 利用率越过它进入拥挤态。0 = 不做判定，开着就一直按拥挤处理。
	CongestionExitPercent  uint32 `protobuf:"varint,5,opt,name=congestion_exit_percent,json=congestionExitPercent,proto3" json:"congestion_exit_percent,omitempty"`    // 回落到它以下才考虑退出。0 或高于 enter 时取 enter。
	CongestionExitTicks    uint32 `protobuf:"varint,6,opt,name=congestion_exit_ticks,json=congestionExitTicks,proto3" json:"congestion_exit_ticks,omitempty"`          // 连续多少个 tick（1 秒）低于 exit 才退出。0 与 1 等价。
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetNodeBandwidthRequest) Reset() {
	*x = SetNodeBandwidthRequest{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeBandwidthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeBandwidthRequest) ProtoMessage() {}

func (x *SetNodeBandwidthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeBandwidthRequest.ProtoReflect.Descriptor instead.
func (*SetNodeBandwidthRequest) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *SetNodeBandwidthRequest) GetAvailBps() uint64 {
	if x != nil {
		return x.AvailBps
	}
	return 0
}

func (x *SetNodeBandwidthRequest) GetCongestionEnterPercent() uint32 {
	if x != nil {
		return x.CongestionEnterPercent
	}
	return 0
}

func (x *SetNodeBandwidthRequest) GetCongestionExitPercent() uint32 {
	if x != nil {
		return x.CongestionExitPercent
	}
	return 0
}

func (x *SetNodeBandwidthRequest) GetCongestionExitTicks() uint32 {
	if x != nil {
		return x.CongestionExitTicks
	}
	return 0
}

type SetNodeBandwidthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNodeBandwidthResponse) Reset() {
	*x = SetNodeBandwidthResponse{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeBandwidthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeBandwidthResponse) ProtoMessage() {}

func (x *SetNodeBandwidthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeBandwidthResponse.ProtoReflect.Descriptor instead.
func (*SetNodeBandwidthResponse) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{1}
}

// ClassPolicy 是一组池共享的争抢参数，只在拥挤态起作用。0 = 没有这一项。
type ClassPolicy struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`      // 与 User.class 精确匹配。
	Weight uint32                 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"` // 拥挤时按它分剩余带宽。0 与 1 等价。
	// class 全体活跃池共享的方向性保底（聚合，不是逐池）；没人用的部分当 tick 回流。
	UploadReservedBytePerSec   uint64 `protobuf:"varint,7,opt,name=upload_reserved_byte_per_sec,json=uploadReservedBytePerSec,proto3" json:"upload_reserved_byte_per_sec,omitempty"`
	DownloadReservedBytePerSec uint64 `protobuf:"varint,8,opt,name=download_reserved_byte_per_sec,json=downloadReservedBytePerSec,proto3" json:"download_reserved_byte_per_sec,omitempty"`
	// 拥挤时每个活跃池的地板（不超过它自己的需求）。整层给得起才给。
	FloorBytePerSec uint64 `protobuf:"varint,10,opt,name=floor_byte_per_sec,json=floorBytePerSec,proto3" json:"floor_byte_per_sec,omitempty"`
	// 重度识别：最近 heavy_window_seconds 秒平均用量 ≥ 标准 × heavy_percent% 的池，
	// 拥挤时保底 = 它的持续速率，剩余带宽排在正常池之后分。任一为 0 = 不识别。
	HeavyWindowSeconds uint32 `protobuf:"varint,11,opt,name=heavy_window_seconds,json=heavyWindowSeconds,proto3" json:"heavy_window_seconds,omitempty"`
	HeavyPercent       uint32 `protobuf:"varint,12,opt,name=heavy_percent,json=heavyPercent,proto3" json:"heavy_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClassPolicy) Reset() {
	*x = ClassPolicy{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassPolicy) ProtoMessage() {}

func (x *ClassPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassPolicy.ProtoReflect.Descriptor instead.
func (*ClassPolicy) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *ClassPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassPolicy) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ClassPolicy) GetUploadReservedBytePerSec() uint64 {
	if x != nil {
		return x.UploadReservedBytePerSec
	}
	return 0
}

func (x *ClassPolicy) GetDownloadReservedBytePerSec() uint64 {
	if x != nil {
		return x.DownloadReservedBytePerSec
	}
	return 0
}

func (x *ClassPolicy) GetFloorBytePerSec() uint64 {
	if x != nil {
		return x.FloorBytePerSec
	}
	return 0
}

func (x *ClassPolicy) GetHeavyWindowSeconds() uint32 {
	if x != nil {
		return x.HeavyWindowSeconds
	}
	return 0
}

func (x *ClassPolicy) GetHeavyPercent() uint32 {
	if x != nil {
		return x.HeavyPercent
	}
	return 0
}

type SetClassPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []*ClassPolicy         `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"` // 整份替换。空列表 = 清空 class 表。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClassPolicyRequest) Reset() {
	*x = SetClassPolicyRequest{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClassPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClassPolicyRequest) ProtoMessage() {}

func (x *SetClassPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClassPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetClassPolicyRequest) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *SetClassPolicyRequest) GetClasses() []*ClassPolicy {
	if x != nil {
		return x.Classes
	}
	return nil
}

type SetClassPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClassPolicyResponse) Reset() {
	*x = SetClassPolicyResponse{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClassPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClassPolicyResponse) ProtoMessage() {}

func (x *SetClassPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClassPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetClassPolicyResponse) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{4}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{5}
}

type GetStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RootCapBytePerSec uint64                 `protobuf:"varint,1,opt,name=root_cap_byte_per_sec,json=rootCapBytePerSec,proto3" json:"root_cap_byte_per_sec,omitempty"` // 0 = 节点级调度没开
	Congested         bool                   `protobuf:"varint,2,opt,name=congested,proto3" json:"congested,omitempty"`                                                // 当前是否处于拥挤态
	ActiveMembers     uint32                 `protobuf:"varint,3,opt,name=active_members,json=activeMembers,proto3" json:"active_members,omitempty"`                   // 最近一 tick 的活跃池数
	// 注水截断：轮数用完还没收敛，余下的按权重一次分完。总额仍不超过 root_cap。
	FillTruncated           bool   `protobuf:"varint,4,opt,name=fill_truncated,json=fillTruncated,proto3" json:"fill_truncated,omitempty"`
	FillUnresolvedMembers   uint32 `protobuf:"varint,5,opt,name=fill_unresolved_members,json=fillUnresolvedMembers,proto3" json:"fill_unresolved_members,omitempty"`
	FillTruncatedTicks      uint64 `protobuf:"varint,6,opt,name=fill_truncated_ticks,json=fillTruncatedTicks,proto3" json:"fill_truncated_ticks,omitempty"`
	FillTruncatedTotalTicks uint64 `protobuf:"varint,7,opt,name=fill_truncated_total_ticks,json=fillTruncatedTotalTicks,proto3" json:"fill_truncated_total_ticks,omitempty"`
	FillRounds              uint32 `protobuf:"varint,8,opt,name=fill_rounds,json=fillRounds,proto3" json:"fill_rounds,omitempty"`
	HeavyMembers            uint32 `protobuf:"varint,9,opt,name=heavy_members,json=heavyMembers,proto3" json:"heavy_members,omitempty"`                                // 活跃池里被识别为重度的个数
	UsedUploadBytePerSec    uint64 `protobuf:"varint,10,opt,name=used_upload_byte_per_sec,json=usedUploadBytePerSec,proto3" json:"used_upload_byte_per_sec,omitempty"` // 最近一 tick 的实测吞吐
	UsedDownloadBytePerSec  uint64 `protobuf:"varint,11,opt,name=used_download_byte_per_sec,json=usedDownloadBytePerSec,proto3" json:"used_download_byte_per_sec,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusResponse) GetRootCapBytePerSec() uint64 {
	if x != nil {
		return x.RootCapBytePerSec
	}
	return 0
}

func (x *GetStatusResponse) GetCongested() bool {
	if x != nil {
		return x.Congested
	}
	return false
}

func (x *GetStatusResponse) GetActiveMembers() uint32 {
	if x != nil {
		return x.ActiveMembers
	}
	return 0
}

func (x *GetStatusResponse) GetFillTruncated() bool {
	if x != nil {
		return x.FillTruncated
	}
	return false
}

func (x *GetStatusResponse) GetFillUnresolvedMembers() uint32 {
	if x != nil {
		return x.FillUnresolvedMembers
	}
	return 0
}

func (x *GetStatusResponse) GetFillTruncatedTicks() uint64 {
	if x != nil {
		return x.FillTruncatedTicks
	}
	return 0
}

func (x *GetStatusResponse) GetFillTruncatedTotalTicks() uint64 {
	if x != nil {
		return x.FillTruncatedTotalTicks
	}
	return 0
}

func (x *GetStatusResponse) GetFillRounds() uint32 {
	if x != nil {
		return x.FillRounds
	}
	return 0
}

func (x *GetStatusResponse) GetHeavyMembers() uint32 {
	if x != nil {
		return x.HeavyMembers
	}
	return 0
}

func (x *GetStatusResponse) GetUsedUploadBytePerSec() uint64 {
	if x != nil {
		return x.UsedUploadBytePerSec
	}
	return 0
}

func (x *GetStatusResponse) GetUsedDownloadBytePerSec() uint64 {
	if x != nil {
		return x.UsedDownloadBytePerSec
	}
	return 0
}

// Config 命令服务配置（gRPC server 经 RegisterConfig 实例化本服务）。
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{7}
}

var File_app_fairshare_command_command_proto protoreflect.FileDescriptor

const file_app_fairshare_command_command_proto_rawDesc = "" +
	"\n" +
	"#app/fairshare/command/command.proto\x12\x1axray.app.fairshare.command\"\xe8\x01\n" +
	"\x17SetNodeBandwidthRequest\x12\x1b\n" +
	"\tavail_bps\x18\x01 \x01(\x04R\bavailBps\x128\n" +
	"\x18congestion_enter_percent\x18\x04 \x01(\rR\x16congestionEnterPercent\x126\n" +
	"\x17congestion_exit_percent\x18\x05 \x01(\rR\x15congestionExitPercent\x122\n" +
	"\x15congestion_exit_ticks\x18\x06 \x01(\rR\x13congestionExitTicksJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"\x1a\n" +
	"\x18SetNodeBandwidthResponse\"\xdf\x02\n" +
	"\vClassPolicy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\x12>\n" +
	"\x1cupload_reserved_byte_per_sec\x18\a \x01(\x04R\x18uploadReservedBytePerSec\x12B\n" +
	"\x1edownload_reserved_byte_per_sec\x18\b \x01(\x04R\x1adownloadReservedBytePerSec\x12+\n" +
	"\x12floor_byte_per_sec\x18\n" +
	" \x01(\x04R\x0ffloorBytePerSec\x120\n" +
	"\x14heavy_window_seconds\x18\v \x01(\rR\x12heavyWindowSeconds\x12#\n" +
	"\rheavy_percent\x18\f \x01(\rR\fheavyPercentJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\t\x10\n" +
	"\"Z\n" +
	"\x15SetClassPolicyRequest\x12A\n" +
	"\aclasses\x18\x01 \x03(\v2'.xray.app.fairshare.command.ClassPolicyR\aclasses\"\x18\n" +
	"\x16SetClassPolicyResponse\"\x12\n" +
	"\x10GetStatusRequest\"\x92\x04\n" +
	"\x11GetStatusResponse\x120\n" +
	"\x15root_cap_byte_per_sec\x18\x01 \x01(\x04R\x11rootCapBytePerSec\x12\x1c\n" +
	"\tcongested\x18\x02 \x01(\bR\tcongested\x12%\n" +
	"\x0eactive_members\x18\x03 \x01(\rR\ractiveMembers\x12%\n" +
	"\x0efill_truncated\x18\x04 \x01(\bR\rfillTruncated\x126\n" +
	"\x17fill_unresolved_members\x18\x05 \x01(\rR\x15fillUnresolvedMembers\x120\n" +
	"\x14fill_truncated_ticks\x18\x06 \x01(\x04R\x12fillTruncatedTicks\x12;\n" +
	"\x1afill_truncated_total_ticks\x18\a \x01(\x04R\x17fillTruncatedTotalTicks\x12\x1f\n" +
	"\vfill_rounds\x18\b \x01(\rR\n" +
	"fillRounds\x12#\n" +
	"\rheavy_members\x18\t \x01(\rR\fheavyMembers\x126\n" +
	"\x18used_upload_byte_per_sec\x18\n" +
	" \x01(\x04R\x14usedUploadBytePerSec\x12:\n" +
	"\x1aused_download_byte_per_sec\x18\v \x01(\x04R\x16usedDownloadBytePerSec\"\b\n" +
	"\x06Config2\xfa\x02\n" +
	"\x10FairShareService\x12\x7f\n" +
	"\x10SetNodeBandwidth\x123.xray.app.fairshare.command.SetNodeBandwidthRequest\x1a4.xray.app.fairshare.command.SetNodeBandwidthResponse\"\x00\x12y\n" +
	"\x0eSetClassPolicy\x121.xray.app.fairshare.command.SetClassPolicyRequest\x1a2.xray.app.fairshare.command.SetClassPolicyResponse\"\x00\x12j\n" +
	"\tGetStatus\x12,.xray.app.fairshare.command.GetStatusRequest\x1a-.xray.app.fairshare.command.GetStatusResponse\"\x00Bp\n" +
	"\x1ecom.xray.app.fairshare.commandP\x01Z/github.com/xtls/xray-core/app/fairshare/command\xaa\x02\x1aXray.App.FairShare.Commandb\x06proto3"

var (
	file_app_fairshare_command_command_proto_rawDescOnce sync.Once
	file_app_fairshare_command_command_proto_rawDescData []byte
)

func file_app_fairshare_command_command_proto_rawDescGZIP() []byte {
	file_app_fairshare_command_command_proto_rawDescOnce.Do(func() {
		file_app_fairshare_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_fairshare_command_command_proto_rawDesc), len(file_app_fairshare_command_command_proto_rawDesc)))
	})
	return file_app_fairshare_command_command_proto_rawDescData
}

var file_app_fairshare_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_app_fairshare_command_command_proto_goTypes = []any{
	(*SetNodeBandwidthRequest)(nil),  // 0: xray.app.fairshare.command.SetNodeBandwidthRequest
	(*SetNodeBandwidthResponse)(nil), // 1: xray.app.fairshare.command.SetNodeBandwidthResponse
	(*ClassPolicy)(nil),              // 2: xray.app.fairshare.command.ClassPolicy
	(*SetClassPolicyRequest)(nil),    // 3: xray.app.fairshare.command.SetClassPolicyRequest
	(*SetClassPolicyResponse)(nil),   // 4: xray.app.fairshare.command.SetClassPolicyResponse
	(*GetStatusRequest)(nil),         // 5: xray.app.fairshare.command.GetStatusRequest
	(*GetStatusResponse)(nil),        // 6: xray.app.fairshare.command.GetStatusResponse
	(*Config)(nil),                   // 7: xray.app.fairshare.command.Config
}
var file_app_fairshare_command_command_proto_depIdxs = []int32{
	2, // 0: xray.app.fairshare.command.SetClassPolicyRequest.classes:type_name -> xray.app.fairshare.command.ClassPolicy
	0, // 1: xray.app.fairshare.command.FairShareService.SetNodeBandwidth:input_type -> xray.app.fairshare.command.SetNodeBandwidthRequest
	3, // 2: xray.app.fairshare.command.FairShareService.SetClassPolicy:input_type -> xray.app.fairshare.command.SetClassPolicyRequest
	5, // 3: xray.app.fairshare.command.FairShareService.GetStatus:input_type -> xray.app.fairshare.command.GetStatusRequest
	1, // 4: xray.app.fairshare.command.FairShareService.SetNodeBandwidth:output_type -> xray.app.fairshare.command.SetNodeBandwidthResponse
	4, // 5: xray.app.fairshare.command.FairShareService.SetClassPolicy:output_type -> xray.app.fairshare.command.SetClassPolicyResponse
	6, // 6: xray.app.fairshare.command.FairShareService.GetStatus:output_type -> xray.app.fairshare.command.GetStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_fairshare_command_command_proto_init() }
func file_app_fairshare_command_command_proto_init() {
	if File_app_fairshare_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_fairshare_command_command_proto_rawDesc), len(file_app_fairshare_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_fairshare_command_command_proto_goTypes,
		DependencyIndexes: file_app_fairshare_command_command_proto_depIdxs,
		MessageInfos:      file_app_fairshare_command_command_proto_msgTypes,
	}.Build()
	File_app_fairshare_command_command_proto = out.File
	file_app_fairshare_command_command_proto_goTypes = nil
	file_app_fairshare_command_command_proto_depIdxs = nil
}
