// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: app/fairshare/command/command.proto

// app.fairshare.command 是 ipipx 魔改：节点级公平限速配置的 gRPC 下发面。
// node-agent 收到 NodeConfig（总带宽 + headroom）后调 SetNodeBandwidth 喂进程内调度器。

package command

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ⚠️ 单位陷阱（FR-079d）：本文件里的 `_bps` 后缀一律是 **字节/秒**，
// 而 common/protocol/user.proto 里 User 的 `bandwidth_bps` / `committed_bps` 是 **比特/秒**。
// 同一个后缀两处含义差 8 倍。这三个历史字段不改名（改名会断掉已经在跑的 node-agent），
// 改为在此写死语义，并由 command_units_test.go / node_fairshare_units_test.go 两条断言测试钉住；
// **新增的速率字段一律带 `_byte_per_sec` / `_bit_per_sec` 后缀**，见下方 ClassPolicy。
// 谁要是「顺手统一成同一单位」，那两条测试会红。
type SetNodeBandwidthRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AvailBps     uint64                 `protobuf:"varint,1,opt,name=avail_bps,json=availBps,proto3" json:"avail_bps,omitempty"`               // root_cap：节点整形上限，**字节/秒** = total_bandwidth_bps × headroom_pct/100。0=关闭节点级公平。
	SoftFloorBps uint64                 `protobuf:"varint,2,opt,name=soft_floor_bps,json=softFloorBps,proto3" json:"soft_floor_bps,omitempty"` // 公平软地板，**字节/秒**。0 = 无软地板（不是「用默认值」，见 FR-079c）。
	HardFloorBps uint64                 `protobuf:"varint,3,opt,name=hard_floor_bps,json=hardFloorBps,proto3" json:"hard_floor_bps,omitempty"` // 绝对硬地板，**字节/秒**。0 = 无硬地板。地板只在 floor×活跃人数 ≤ root_cap 时生效。
	// 拥塞滞回（FR-076）。都是百分比/计数，没有单位歧义，故不带单位后缀。
	CongestionEnterPercent uint32 `protobuf:"varint,4,opt,name=congestion_enter_percent,json=congestionEnterPercent,proto3" json:"congestion_enter_percent,omitempty"` // 节点利用率越过该百分比才进入公平模式。0 = 不做拥塞判定，永远公平模式（= 改造前行为）。
	CongestionExitPercent  uint32 `protobuf:"varint,5,opt,name=congestion_exit_percent,json=congestionExitPercent,proto3" json:"congestion_exit_percent,omitempty"`    // 回落到该百分比以下才考虑退出。0 或高于 enter 时取 enter。
	CongestionExitTicks    uint32 `protobuf:"varint,6,opt,name=congestion_exit_ticks,json=congestionExitTicks,proto3" json:"congestion_exit_ticks,omitempty"`          // 需连续多少个 tick（1 tick = 1 秒）低于 exit 才真的退出。0 视为 1。
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetNodeBandwidthRequest) Reset() {
	*x = SetNodeBandwidthRequest{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeBandwidthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeBandwidthRequest) ProtoMessage() {}

func (x *SetNodeBandwidthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeBandwidthRequest.ProtoReflect.Descriptor instead.
func (*SetNodeBandwidthRequest) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *SetNodeBandwidthRequest) GetAvailBps() uint64 {
	if x != nil {
		return x.AvailBps
	}
	return 0
}

func (x *SetNodeBandwidthRequest) GetSoftFloorBps() uint64 {
	if x != nil {
		return x.SoftFloorBps
	}
	return 0
}

func (x *SetNodeBandwidthRequest) GetHardFloorBps() uint64 {
	if x != nil {
		return x.HardFloorBps
	}
	return 0
}

func (x *SetNodeBandwidthRequest) GetCongestionEnterPercent() uint32 {
	if x != nil {
		return x.CongestionEnterPercent
	}
	return 0
}

func (x *SetNodeBandwidthRequest) GetCongestionExitPercent() uint32 {
	if x != nil {
		return x.CongestionExitPercent
	}
	return 0
}

func (x *SetNodeBandwidthRequest) GetCongestionExitTicks() uint32 {
	if x != nil {
		return x.CongestionExitTicks
	}
	return 0
}

type SetNodeBandwidthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNodeBandwidthResponse) Reset() {
	*x = SetNodeBandwidthResponse{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeBandwidthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeBandwidthResponse) ProtoMessage() {}

func (x *SetNodeBandwidthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeBandwidthResponse.ProtoReflect.Descriptor instead.
func (*SetNodeBandwidthResponse) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{1}
}

// ClassPolicy 是一组客户共享的争抢策略。
// class 名字挂在 User.class 上随实例下发；这张表是运营参数，不进客户界面（FR-079f）。
type ClassPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // class 名，与 User.class 对应。空名 = 未分类用户的兜底策略。
	// 拥塞时按 weight 分剩余带宽。0 视为 1。直播应高于短视频。
	Weight uint32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// normal_cap：**不拥挤时**这个 class 的单客户最高速率，字节/秒。
	// ⚠️ 这不是保证带宽/CIR（FR-071）：500 客户 × 20Mbps = 10Gbps，物理上不可能承诺。
	// 0 = 该 class 不设 class 级上限（仍受客户自己的 PIR/CIR 与 root_cap 约束）。
	NormalCapBytePerSec uint64 `protobuf:"varint,3,opt,name=normal_cap_byte_per_sec,json=normalCapBytePerSec,proto3" json:"normal_cap_byte_per_sec,omitempty"`
	// burst_cap：持有突发信用时能冲到的峰值，字节/秒。必须 > normal_cap 才有意义。
	// 0 = 该 class 不给突发。
	BurstCapBytePerSec uint64 `protobuf:"varint,4,opt,name=burst_cap_byte_per_sec,json=burstCapBytePerSec,proto3" json:"burst_cap_byte_per_sec,omitempty"`
	// burst_credit_bytes：突发信用桶容量（字节）。信用只按「超出 normal_cap 的那部分字节」
	// 扣（FR-078）；低于 normal_cap 时按未用满的差额回补。0 = 不给突发。
	BurstCreditBytes uint64 `protobuf:"varint,5,opt,name=burst_credit_bytes,json=burstCreditBytes,proto3" json:"burst_credit_bytes,omitempty"`
	// floor_ratio_percent：该 class 的地板 = normal_cap × 该百分比。
	// 与全局软地板取较大者，且仍受「地板×活跃人数 ≤ root_cap 才生效」的前提约束（FR-077）。
	// 0 = 该 class 无专属地板。
	FloorRatioPercent uint32 `protobuf:"varint,6,opt,name=floor_ratio_percent,json=floorRatioPercent,proto3" json:"floor_ratio_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClassPolicy) Reset() {
	*x = ClassPolicy{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassPolicy) ProtoMessage() {}

func (x *ClassPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassPolicy.ProtoReflect.Descriptor instead.
func (*ClassPolicy) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *ClassPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassPolicy) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ClassPolicy) GetNormalCapBytePerSec() uint64 {
	if x != nil {
		return x.NormalCapBytePerSec
	}
	return 0
}

func (x *ClassPolicy) GetBurstCapBytePerSec() uint64 {
	if x != nil {
		return x.BurstCapBytePerSec
	}
	return 0
}

func (x *ClassPolicy) GetBurstCreditBytes() uint64 {
	if x != nil {
		return x.BurstCreditBytes
	}
	return 0
}

func (x *ClassPolicy) GetFloorRatioPercent() uint32 {
	if x != nil {
		return x.FloorRatioPercent
	}
	return 0
}

type SetClassPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []*ClassPolicy         `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"` // 整份替换。空列表 = 清空 class 表（全员同权重、无 class 上限）。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClassPolicyRequest) Reset() {
	*x = SetClassPolicyRequest{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClassPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClassPolicyRequest) ProtoMessage() {}

func (x *SetClassPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClassPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetClassPolicyRequest) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *SetClassPolicyRequest) GetClasses() []*ClassPolicy {
	if x != nil {
		return x.Classes
	}
	return nil
}

type SetClassPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClassPolicyResponse) Reset() {
	*x = SetClassPolicyResponse{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClassPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClassPolicyResponse) ProtoMessage() {}

func (x *SetClassPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClassPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetClassPolicyResponse) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{4}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{5}
}

type GetStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RootCapBytePerSec uint64                 `protobuf:"varint,1,opt,name=root_cap_byte_per_sec,json=rootCapBytePerSec,proto3" json:"root_cap_byte_per_sec,omitempty"` // 节点整形上限；0 = 节点级公平没开
	Congested         bool                   `protobuf:"varint,2,opt,name=congested,proto3" json:"congested,omitempty"`                                                // 当前是否处于公平模式（不拥塞时根本不削速）
	ActiveMembers     uint32                 `protobuf:"varint,3,opt,name=active_members,json=activeMembers,proto3" json:"active_members,omitempty"`                   // 最近一 tick 的活跃成员数
	// 注水截断（成员极多且天花板各不相同时，轮数用完还没收敛，余下按权重一次分完）。
	// 总额仍不超过 root_cap，但那批成员之间的公平性是近似的。
	// 这四个字段回答运维的三个问题：这一 tick 截断了吗 · 还剩多少成员没轮到 · 持续多久了。
	FillTruncated           bool   `protobuf:"varint,4,opt,name=fill_truncated,json=fillTruncated,proto3" json:"fill_truncated,omitempty"`
	FillUnresolvedMembers   uint32 `protobuf:"varint,5,opt,name=fill_unresolved_members,json=fillUnresolvedMembers,proto3" json:"fill_unresolved_members,omitempty"`         // 在 active_members 里的占比才是重点
	FillTruncatedTicks      uint64 `protobuf:"varint,6,opt,name=fill_truncated_ticks,json=fillTruncatedTicks,proto3" json:"fill_truncated_ticks,omitempty"`                  // 已连续截断多少 tick（1 tick = 1 秒）；0 = 当前没截断
	FillTruncatedTotalTicks uint64 `protobuf:"varint,7,opt,name=fill_truncated_total_ticks,json=fillTruncatedTotalTicks,proto3" json:"fill_truncated_total_ticks,omitempty"` // 进程启动以来累计
	FillRounds              uint32 `protobuf:"varint,8,opt,name=fill_rounds,json=fillRounds,proto3" json:"fill_rounds,omitempty"`                                            // 最近一 tick 实际跑了几轮；等于上限就是撞顶了
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusResponse) GetRootCapBytePerSec() uint64 {
	if x != nil {
		return x.RootCapBytePerSec
	}
	return 0
}

func (x *GetStatusResponse) GetCongested() bool {
	if x != nil {
		return x.Congested
	}
	return false
}

func (x *GetStatusResponse) GetActiveMembers() uint32 {
	if x != nil {
		return x.ActiveMembers
	}
	return 0
}

func (x *GetStatusResponse) GetFillTruncated() bool {
	if x != nil {
		return x.FillTruncated
	}
	return false
}

func (x *GetStatusResponse) GetFillUnresolvedMembers() uint32 {
	if x != nil {
		return x.FillUnresolvedMembers
	}
	return 0
}

func (x *GetStatusResponse) GetFillTruncatedTicks() uint64 {
	if x != nil {
		return x.FillTruncatedTicks
	}
	return 0
}

func (x *GetStatusResponse) GetFillTruncatedTotalTicks() uint64 {
	if x != nil {
		return x.FillTruncatedTotalTicks
	}
	return 0
}

func (x *GetStatusResponse) GetFillRounds() uint32 {
	if x != nil {
		return x.FillRounds
	}
	return 0
}

// Config 命令服务配置（gRPC server 经 RegisterConfig 实例化本服务）。
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_fairshare_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_fairshare_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_fairshare_command_command_proto_rawDescGZIP(), []int{7}
}

var File_app_fairshare_command_command_proto protoreflect.FileDescriptor

const file_app_fairshare_command_command_proto_rawDesc = "" +
	"\n" +
	"#app/fairshare/command/command.proto\x12\x1axray.app.fairshare.command\"\xa8\x02\n" +
	"\x17SetNodeBandwidthRequest\x12\x1b\n" +
	"\tavail_bps\x18\x01 \x01(\x04R\bavailBps\x12$\n" +
	"\x0esoft_floor_bps\x18\x02 \x01(\x04R\fsoftFloorBps\x12$\n" +
	"\x0ehard_floor_bps\x18\x03 \x01(\x04R\fhardFloorBps\x128\n" +
	"\x18congestion_enter_percent\x18\x04 \x01(\rR\x16congestionEnterPercent\x126\n" +
	"\x17congestion_exit_percent\x18\x05 \x01(\rR\x15congestionExitPercent\x122\n" +
	"\x15congestion_exit_ticks\x18\x06 \x01(\rR\x13congestionExitTicks\"\x1a\n" +
	"\x18SetNodeBandwidthResponse\"\x81\x02\n" +
	"\vClassPolicy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\x124\n" +
	"\x17normal_cap_byte_per_sec\x18\x03 \x01(\x04R\x13normalCapBytePerSec\x122\n" +
	"\x16burst_cap_byte_per_sec\x18\x04 \x01(\x04R\x12burstCapBytePerSec\x12,\n" +
	"\x12burst_credit_bytes\x18\x05 \x01(\x04R\x10burstCreditBytes\x12.\n" +
	"\x13floor_ratio_percent\x18\x06 \x01(\rR\x11floorRatioPercent\"Z\n" +
	"\x15SetClassPolicyRequest\x12A\n" +
	"\aclasses\x18\x01 \x03(\v2'.xray.app.fairshare.command.ClassPolicyR\aclasses\"\x18\n" +
	"\x16SetClassPolicyResponse\"\x12\n" +
	"\x10GetStatusRequest\"\xf9\x02\n" +
	"\x11GetStatusResponse\x120\n" +
	"\x15root_cap_byte_per_sec\x18\x01 \x01(\x04R\x11rootCapBytePerSec\x12\x1c\n" +
	"\tcongested\x18\x02 \x01(\bR\tcongested\x12%\n" +
	"\x0eactive_members\x18\x03 \x01(\rR\ractiveMembers\x12%\n" +
	"\x0efill_truncated\x18\x04 \x01(\bR\rfillTruncated\x126\n" +
	"\x17fill_unresolved_members\x18\x05 \x01(\rR\x15fillUnresolvedMembers\x120\n" +
	"\x14fill_truncated_ticks\x18\x06 \x01(\x04R\x12fillTruncatedTicks\x12;\n" +
	"\x1afill_truncated_total_ticks\x18\a \x01(\x04R\x17fillTruncatedTotalTicks\x12\x1f\n" +
	"\vfill_rounds\x18\b \x01(\rR\n" +
	"fillRounds\"\b\n" +
	"\x06Config2\xfa\x02\n" +
	"\x10FairShareService\x12\x7f\n" +
	"\x10SetNodeBandwidth\x123.xray.app.fairshare.command.SetNodeBandwidthRequest\x1a4.xray.app.fairshare.command.SetNodeBandwidthResponse\"\x00\x12y\n" +
	"\x0eSetClassPolicy\x121.xray.app.fairshare.command.SetClassPolicyRequest\x1a2.xray.app.fairshare.command.SetClassPolicyResponse\"\x00\x12j\n" +
	"\tGetStatus\x12,.xray.app.fairshare.command.GetStatusRequest\x1a-.xray.app.fairshare.command.GetStatusResponse\"\x00Bp\n" +
	"\x1ecom.xray.app.fairshare.commandP\x01Z/github.com/xtls/xray-core/app/fairshare/command\xaa\x02\x1aXray.App.FairShare.Commandb\x06proto3"

var (
	file_app_fairshare_command_command_proto_rawDescOnce sync.Once
	file_app_fairshare_command_command_proto_rawDescData []byte
)

func file_app_fairshare_command_command_proto_rawDescGZIP() []byte {
	file_app_fairshare_command_command_proto_rawDescOnce.Do(func() {
		file_app_fairshare_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_fairshare_command_command_proto_rawDesc), len(file_app_fairshare_command_command_proto_rawDesc)))
	})
	return file_app_fairshare_command_command_proto_rawDescData
}

var file_app_fairshare_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_app_fairshare_command_command_proto_goTypes = []any{
	(*SetNodeBandwidthRequest)(nil),  // 0: xray.app.fairshare.command.SetNodeBandwidthRequest
	(*SetNodeBandwidthResponse)(nil), // 1: xray.app.fairshare.command.SetNodeBandwidthResponse
	(*ClassPolicy)(nil),              // 2: xray.app.fairshare.command.ClassPolicy
	(*SetClassPolicyRequest)(nil),    // 3: xray.app.fairshare.command.SetClassPolicyRequest
	(*SetClassPolicyResponse)(nil),   // 4: xray.app.fairshare.command.SetClassPolicyResponse
	(*GetStatusRequest)(nil),         // 5: xray.app.fairshare.command.GetStatusRequest
	(*GetStatusResponse)(nil),        // 6: xray.app.fairshare.command.GetStatusResponse
	(*Config)(nil),                   // 7: xray.app.fairshare.command.Config
}
var file_app_fairshare_command_command_proto_depIdxs = []int32{
	2, // 0: xray.app.fairshare.command.SetClassPolicyRequest.classes:type_name -> xray.app.fairshare.command.ClassPolicy
	0, // 1: xray.app.fairshare.command.FairShareService.SetNodeBandwidth:input_type -> xray.app.fairshare.command.SetNodeBandwidthRequest
	3, // 2: xray.app.fairshare.command.FairShareService.SetClassPolicy:input_type -> xray.app.fairshare.command.SetClassPolicyRequest
	5, // 3: xray.app.fairshare.command.FairShareService.GetStatus:input_type -> xray.app.fairshare.command.GetStatusRequest
	1, // 4: xray.app.fairshare.command.FairShareService.SetNodeBandwidth:output_type -> xray.app.fairshare.command.SetNodeBandwidthResponse
	4, // 5: xray.app.fairshare.command.FairShareService.SetClassPolicy:output_type -> xray.app.fairshare.command.SetClassPolicyResponse
	6, // 6: xray.app.fairshare.command.FairShareService.GetStatus:output_type -> xray.app.fairshare.command.GetStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_fairshare_command_command_proto_init() }
func file_app_fairshare_command_command_proto_init() {
	if File_app_fairshare_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_fairshare_command_command_proto_rawDesc), len(file_app_fairshare_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_fairshare_command_command_proto_goTypes,
		DependencyIndexes: file_app_fairshare_command_command_proto_depIdxs,
		MessageInfos:      file_app_fairshare_command_command_proto_msgTypes,
	}.Build()
	File_app_fairshare_command_command_proto = out.File
	file_app_fairshare_command_command_proto_goTypes = nil
	file_app_fairshare_command_command_proto_depIdxs = nil
}
