// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: app/reverse/command/command.proto

// app.reverse.command 是 ipipx 魔改：reverse（内网穿透的 bridge/portal）的
// gRPC 热改面。
//
// 为什么需要它：控制面给客户换入口是常规操作。如果每次都要重启 xray 进程，
// 那台节点上**所有**客户的连接会一起断——一个客户改配置，全节点陪着断线。
// 热改是产品要求，不是优化。

package command

import (
	reverse "github.com/xtls/xray-core/app/reverse"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridge        *reverse.BridgeConfig  `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBridgeRequest) Reset() {
	*x = AddBridgeRequest{}
	mi := &file_app_reverse_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBridgeRequest) ProtoMessage() {}

func (x *AddBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBridgeRequest.ProtoReflect.Descriptor instead.
func (*AddBridgeRequest) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *AddBridgeRequest) GetBridge() *reverse.BridgeConfig {
	if x != nil {
		return x.Bridge
	}
	return nil
}

type AddBridgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBridgeResponse) Reset() {
	*x = AddBridgeResponse{}
	mi := &file_app_reverse_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBridgeResponse) ProtoMessage() {}

func (x *AddBridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBridgeResponse.ProtoReflect.Descriptor instead.
func (*AddBridgeResponse) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{1}
}

type RemoveBridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBridgeRequest) Reset() {
	*x = RemoveBridgeRequest{}
	mi := &file_app_reverse_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBridgeRequest) ProtoMessage() {}

func (x *RemoveBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBridgeRequest.ProtoReflect.Descriptor instead.
func (*RemoveBridgeRequest) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveBridgeRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type RemoveBridgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBridgeResponse) Reset() {
	*x = RemoveBridgeResponse{}
	mi := &file_app_reverse_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBridgeResponse) ProtoMessage() {}

func (x *RemoveBridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBridgeResponse.ProtoReflect.Descriptor instead.
func (*RemoveBridgeResponse) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{3}
}

type AddPortalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Portal        *reverse.PortalConfig  `protobuf:"bytes,1,opt,name=portal,proto3" json:"portal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPortalRequest) Reset() {
	*x = AddPortalRequest{}
	mi := &file_app_reverse_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPortalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPortalRequest) ProtoMessage() {}

func (x *AddPortalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPortalRequest.ProtoReflect.Descriptor instead.
func (*AddPortalRequest) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *AddPortalRequest) GetPortal() *reverse.PortalConfig {
	if x != nil {
		return x.Portal
	}
	return nil
}

type AddPortalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPortalResponse) Reset() {
	*x = AddPortalResponse{}
	mi := &file_app_reverse_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPortalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPortalResponse) ProtoMessage() {}

func (x *AddPortalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPortalResponse.ProtoReflect.Descriptor instead.
func (*AddPortalResponse) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{5}
}

type RemovePortalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePortalRequest) Reset() {
	*x = RemovePortalRequest{}
	mi := &file_app_reverse_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePortalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePortalRequest) ProtoMessage() {}

func (x *RemovePortalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePortalRequest.ProtoReflect.Descriptor instead.
func (*RemovePortalRequest) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *RemovePortalRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type RemovePortalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePortalResponse) Reset() {
	*x = RemovePortalResponse{}
	mi := &file_app_reverse_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePortalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePortalResponse) ProtoMessage() {}

func (x *RemovePortalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePortalResponse.ProtoReflect.Descriptor instead.
func (*RemovePortalResponse) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{7}
}

type ListReverseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReverseRequest) Reset() {
	*x = ListReverseRequest{}
	mi := &file_app_reverse_command_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReverseRequest) ProtoMessage() {}

func (x *ListReverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReverseRequest.ProtoReflect.Descriptor instead.
func (*ListReverseRequest) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{8}
}

type ListReverseResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Bridges       []*reverse.BridgeConfig `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"`
	Portals       []*reverse.PortalConfig `protobuf:"bytes,2,rep,name=portals,proto3" json:"portals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReverseResponse) Reset() {
	*x = ListReverseResponse{}
	mi := &file_app_reverse_command_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReverseResponse) ProtoMessage() {}

func (x *ListReverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReverseResponse.ProtoReflect.Descriptor instead.
func (*ListReverseResponse) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{9}
}

func (x *ListReverseResponse) GetBridges() []*reverse.BridgeConfig {
	if x != nil {
		return x.Bridges
	}
	return nil
}

func (x *ListReverseResponse) GetPortals() []*reverse.PortalConfig {
	if x != nil {
		return x.Portals
	}
	return nil
}

// Config 命令服务配置（gRPC server 经 RegisterConfig 实例化本服务）。
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_reverse_command_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{10}
}

var File_app_reverse_command_command_proto protoreflect.FileDescriptor

const file_app_reverse_command_command_proto_rawDesc = "" +
	"\n" +
	"!app/reverse/command/command.proto\x12\x18xray.app.reverse.command\x1a\x18app/reverse/config.proto\"J\n" +
	"\x10AddBridgeRequest\x126\n" +
	"\x06bridge\x18\x01 \x01(\v2\x1e.xray.app.reverse.BridgeConfigR\x06bridge\"\x13\n" +
	"\x11AddBridgeResponse\"'\n" +
	"\x13RemoveBridgeRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"\x16\n" +
	"\x14RemoveBridgeResponse\"J\n" +
	"\x10AddPortalRequest\x126\n" +
	"\x06portal\x18\x01 \x01(\v2\x1e.xray.app.reverse.PortalConfigR\x06portal\"\x13\n" +
	"\x11AddPortalResponse\"'\n" +
	"\x13RemovePortalRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"\x16\n" +
	"\x14RemovePortalResponse\"\x14\n" +
	"\x12ListReverseRequest\"\x89\x01\n" +
	"\x13ListReverseResponse\x128\n" +
	"\abridges\x18\x01 \x03(\v2\x1e.xray.app.reverse.BridgeConfigR\abridges\x128\n" +
	"\aportals\x18\x02 \x03(\v2\x1e.xray.app.reverse.PortalConfigR\aportals\"\b\n" +
	"\x06Config2\xb0\x04\n" +
	"\x0eReverseService\x12f\n" +
	"\tAddBridge\x12*.xray.app.reverse.command.AddBridgeRequest\x1a+.xray.app.reverse.command.AddBridgeResponse\"\x00\x12o\n" +
	"\fRemoveBridge\x12-.xray.app.reverse.command.RemoveBridgeRequest\x1a..xray.app.reverse.command.RemoveBridgeResponse\"\x00\x12f\n" +
	"\tAddPortal\x12*.xray.app.reverse.command.AddPortalRequest\x1a+.xray.app.reverse.command.AddPortalResponse\"\x00\x12o\n" +
	"\fRemovePortal\x12-.xray.app.reverse.command.RemovePortalRequest\x1a..xray.app.reverse.command.RemovePortalResponse\"\x00\x12l\n" +
	"\vListReverse\x12,.xray.app.reverse.command.ListReverseRequest\x1a-.xray.app.reverse.command.ListReverseResponse\"\x00Bj\n" +
	"\x1ccom.xray.app.reverse.commandP\x01Z-github.com/xtls/xray-core/app/reverse/command\xaa\x02\x18Xray.App.Reverse.Commandb\x06proto3"

var (
	file_app_reverse_command_command_proto_rawDescOnce sync.Once
	file_app_reverse_command_command_proto_rawDescData []byte
)

func file_app_reverse_command_command_proto_rawDescGZIP() []byte {
	file_app_reverse_command_command_proto_rawDescOnce.Do(func() {
		file_app_reverse_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_reverse_command_command_proto_rawDesc), len(file_app_reverse_command_command_proto_rawDesc)))
	})
	return file_app_reverse_command_command_proto_rawDescData
}

var file_app_reverse_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_app_reverse_command_command_proto_goTypes = []any{
	(*AddBridgeRequest)(nil),     // 0: xray.app.reverse.command.AddBridgeRequest
	(*AddBridgeResponse)(nil),    // 1: xray.app.reverse.command.AddBridgeResponse
	(*RemoveBridgeRequest)(nil),  // 2: xray.app.reverse.command.RemoveBridgeRequest
	(*RemoveBridgeResponse)(nil), // 3: xray.app.reverse.command.RemoveBridgeResponse
	(*AddPortalRequest)(nil),     // 4: xray.app.reverse.command.AddPortalRequest
	(*AddPortalResponse)(nil),    // 5: xray.app.reverse.command.AddPortalResponse
	(*RemovePortalRequest)(nil),  // 6: xray.app.reverse.command.RemovePortalRequest
	(*RemovePortalResponse)(nil), // 7: xray.app.reverse.command.RemovePortalResponse
	(*ListReverseRequest)(nil),   // 8: xray.app.reverse.command.ListReverseRequest
	(*ListReverseResponse)(nil),  // 9: xray.app.reverse.command.ListReverseResponse
	(*Config)(nil),               // 10: xray.app.reverse.command.Config
	(*reverse.BridgeConfig)(nil), // 11: xray.app.reverse.BridgeConfig
	(*reverse.PortalConfig)(nil), // 12: xray.app.reverse.PortalConfig
}
var file_app_reverse_command_command_proto_depIdxs = []int32{
	11, // 0: xray.app.reverse.command.AddBridgeRequest.bridge:type_name -> xray.app.reverse.BridgeConfig
	12, // 1: xray.app.reverse.command.AddPortalRequest.portal:type_name -> xray.app.reverse.PortalConfig
	11, // 2: xray.app.reverse.command.ListReverseResponse.bridges:type_name -> xray.app.reverse.BridgeConfig
	12, // 3: xray.app.reverse.command.ListReverseResponse.portals:type_name -> xray.app.reverse.PortalConfig
	0,  // 4: xray.app.reverse.command.ReverseService.AddBridge:input_type -> xray.app.reverse.command.AddBridgeRequest
	2,  // 5: xray.app.reverse.command.ReverseService.RemoveBridge:input_type -> xray.app.reverse.command.RemoveBridgeRequest
	4,  // 6: xray.app.reverse.command.ReverseService.AddPortal:input_type -> xray.app.reverse.command.AddPortalRequest
	6,  // 7: xray.app.reverse.command.ReverseService.RemovePortal:input_type -> xray.app.reverse.command.RemovePortalRequest
	8,  // 8: xray.app.reverse.command.ReverseService.ListReverse:input_type -> xray.app.reverse.command.ListReverseRequest
	1,  // 9: xray.app.reverse.command.ReverseService.AddBridge:output_type -> xray.app.reverse.command.AddBridgeResponse
	3,  // 10: xray.app.reverse.command.ReverseService.RemoveBridge:output_type -> xray.app.reverse.command.RemoveBridgeResponse
	5,  // 11: xray.app.reverse.command.ReverseService.AddPortal:output_type -> xray.app.reverse.command.AddPortalResponse
	7,  // 12: xray.app.reverse.command.ReverseService.RemovePortal:output_type -> xray.app.reverse.command.RemovePortalResponse
	9,  // 13: xray.app.reverse.command.ReverseService.ListReverse:output_type -> xray.app.reverse.command.ListReverseResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_app_reverse_command_command_proto_init() }
func file_app_reverse_command_command_proto_init() {
	if File_app_reverse_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_reverse_command_command_proto_rawDesc), len(file_app_reverse_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_reverse_command_command_proto_goTypes,
		DependencyIndexes: file_app_reverse_command_command_proto_depIdxs,
		MessageInfos:      file_app_reverse_command_command_proto_msgTypes,
	}.Build()
	File_app_reverse_command_command_proto = out.File
	file_app_reverse_command_command_proto_goTypes = nil
	file_app_reverse_command_command_proto_depIdxs = nil
}
