// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.3
// source: app/reverse/command/command.proto

// app.reverse.command 是 ipipx 魔改：reverse（内网穿透的 bridge/portal）的
// gRPC 热改面。
//
// 为什么需要它：API 调用方切换入口是常规操作。如果每次都要重启 xray 进程，
// 那台节点上**所有**客户的连接会一起断——一个客户改配置，全节点陪着断线。
// 热改是产品要求，不是优化。

package command

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReverseService_AddBridge_FullMethodName    = "/xray.app.reverse.command.ReverseService/AddBridge"
	ReverseService_RemoveBridge_FullMethodName = "/xray.app.reverse.command.ReverseService/RemoveBridge"
	ReverseService_AddPortal_FullMethodName    = "/xray.app.reverse.command.ReverseService/AddPortal"
	ReverseService_RemovePortal_FullMethodName = "/xray.app.reverse.command.ReverseService/RemovePortal"
	ReverseService_ListReverse_FullMethodName  = "/xray.app.reverse.command.ReverseService/ListReverse"
)

// ReverseServiceClient is the client API for ReverseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverseServiceClient interface {
	// AddBridge 热加一个 bridge。tag 已存在时报错，不静默覆盖。
	AddBridge(ctx context.Context, in *AddBridgeRequest, opts ...grpc.CallOption) (*AddBridgeResponse, error)
	// RemoveBridge 停掉一个 bridge：它不再建新的 worker，存量连接自然收敛。
	RemoveBridge(ctx context.Context, in *RemoveBridgeRequest, opts ...grpc.CallOption) (*RemoveBridgeResponse, error)
	// AddPortal 热加一个 portal，并把它注册进 outbound manager。
	AddPortal(ctx context.Context, in *AddPortalRequest, opts ...grpc.CallOption) (*AddPortalResponse, error)
	// RemovePortal 摘掉一个 portal，连同它的 outbound handler。
	RemovePortal(ctx context.Context, in *RemovePortalRequest, opts ...grpc.CallOption) (*RemovePortalResponse, error)
	// ListReverse 返回当前**运行中**的 bridge/portal，API 调用方靠它确认改动生效了。
	ListReverse(ctx context.Context, in *ListReverseRequest, opts ...grpc.CallOption) (*ListReverseResponse, error)
}

type reverseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReverseServiceClient(cc grpc.ClientConnInterface) ReverseServiceClient {
	return &reverseServiceClient{cc}
}

func (c *reverseServiceClient) AddBridge(ctx context.Context, in *AddBridgeRequest, opts ...grpc.CallOption) (*AddBridgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBridgeResponse)
	err := c.cc.Invoke(ctx, ReverseService_AddBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseServiceClient) RemoveBridge(ctx context.Context, in *RemoveBridgeRequest, opts ...grpc.CallOption) (*RemoveBridgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBridgeResponse)
	err := c.cc.Invoke(ctx, ReverseService_RemoveBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseServiceClient) AddPortal(ctx context.Context, in *AddPortalRequest, opts ...grpc.CallOption) (*AddPortalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPortalResponse)
	err := c.cc.Invoke(ctx, ReverseService_AddPortal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseServiceClient) RemovePortal(ctx context.Context, in *RemovePortalRequest, opts ...grpc.CallOption) (*RemovePortalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePortalResponse)
	err := c.cc.Invoke(ctx, ReverseService_RemovePortal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseServiceClient) ListReverse(ctx context.Context, in *ListReverseRequest, opts ...grpc.CallOption) (*ListReverseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReverseResponse)
	err := c.cc.Invoke(ctx, ReverseService_ListReverse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReverseServiceServer is the server API for ReverseService service.
// All implementations must embed UnimplementedReverseServiceServer
// for forward compatibility.
type ReverseServiceServer interface {
	// AddBridge 热加一个 bridge。tag 已存在时报错，不静默覆盖。
	AddBridge(context.Context, *AddBridgeRequest) (*AddBridgeResponse, error)
	// RemoveBridge 停掉一个 bridge：它不再建新的 worker，存量连接自然收敛。
	RemoveBridge(context.Context, *RemoveBridgeRequest) (*RemoveBridgeResponse, error)
	// AddPortal 热加一个 portal，并把它注册进 outbound manager。
	AddPortal(context.Context, *AddPortalRequest) (*AddPortalResponse, error)
	// RemovePortal 摘掉一个 portal，连同它的 outbound handler。
	RemovePortal(context.Context, *RemovePortalRequest) (*RemovePortalResponse, error)
	// ListReverse 返回当前**运行中**的 bridge/portal，API 调用方靠它确认改动生效了。
	ListReverse(context.Context, *ListReverseRequest) (*ListReverseResponse, error)
	mustEmbedUnimplementedReverseServiceServer()
}

// UnimplementedReverseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReverseServiceServer struct{}

func (UnimplementedReverseServiceServer) AddBridge(context.Context, *AddBridgeRequest) (*AddBridgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBridge not implemented")
}
func (UnimplementedReverseServiceServer) RemoveBridge(context.Context, *RemoveBridgeRequest) (*RemoveBridgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBridge not implemented")
}
func (UnimplementedReverseServiceServer) AddPortal(context.Context, *AddPortalRequest) (*AddPortalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPortal not implemented")
}
func (UnimplementedReverseServiceServer) RemovePortal(context.Context, *RemovePortalRequest) (*RemovePortalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePortal not implemented")
}
func (UnimplementedReverseServiceServer) ListReverse(context.Context, *ListReverseRequest) (*ListReverseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReverse not implemented")
}
func (UnimplementedReverseServiceServer) mustEmbedUnimplementedReverseServiceServer() {}
func (UnimplementedReverseServiceServer) testEmbeddedByValue()                        {}

// UnsafeReverseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverseServiceServer will
// result in compilation errors.
type UnsafeReverseServiceServer interface {
	mustEmbedUnimplementedReverseServiceServer()
}

func RegisterReverseServiceServer(s grpc.ServiceRegistrar, srv ReverseServiceServer) {
	// If the following call panics, it indicates UnimplementedReverseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReverseService_ServiceDesc, srv)
}

func _ReverseService_AddBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseServiceServer).AddBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseService_AddBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseServiceServer).AddBridge(ctx, req.(*AddBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseService_RemoveBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseServiceServer).RemoveBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseService_RemoveBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseServiceServer).RemoveBridge(ctx, req.(*RemoveBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseService_AddPortal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPortalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseServiceServer).AddPortal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseService_AddPortal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseServiceServer).AddPortal(ctx, req.(*AddPortalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseService_RemovePortal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePortalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseServiceServer).RemovePortal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseService_RemovePortal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseServiceServer).RemovePortal(ctx, req.(*RemovePortalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseService_ListReverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseServiceServer).ListReverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseService_ListReverse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseServiceServer).ListReverse(ctx, req.(*ListReverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReverseService_ServiceDesc is the grpc.ServiceDesc for ReverseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReverseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xray.app.reverse.command.ReverseService",
	HandlerType: (*ReverseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBridge",
			Handler:    _ReverseService_AddBridge_Handler,
		},
		{
			MethodName: "RemoveBridge",
			Handler:    _ReverseService_RemoveBridge_Handler,
		},
		{
			MethodName: "AddPortal",
			Handler:    _ReverseService_AddPortal_Handler,
		},
		{
			MethodName: "RemovePortal",
			Handler:    _ReverseService_RemovePortal_Handler,
		},
		{
			MethodName: "ListReverse",
			Handler:    _ReverseService_ListReverse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/reverse/command/command.proto",
}
