// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: common/protocol/user.proto

package protocol

import (
	serial "github.com/xtls/xray-core/common/serial"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User is a generic user for all protocols.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Level uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Email string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Protocol specific account information. Must be the account proto in one of
	// the proxies.
	Account *serial.TypedMessage `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// Top-level, protocol-agnostic per-user runtime limits. Carried on User (not
	// inside the protocol account) so EVERY inbound — mixed/socks/http, vless,
	// shadowsocks, trojan — gets the same limits uniformly through ToMemoryUser,
	// instead of each protocol re-implementing a RuntimeLimits() account method.
	// 0 means unlimited. Bandwidth + connection cap + fair-share all key off the
	// resulting *MemoryUser, so the dispatcher enforces them with no protocol code.
	BandwidthBps uint64 `protobuf:"varint,4,opt,name=bandwidth_bps,json=bandwidthBps,proto3" json:"bandwidth_bps,omitempty"`
	ConnLimit    uint32 `protobuf:"varint,5,opt,name=conn_limit,json=connLimit,proto3" json:"conn_limit,omitempty"`
	// Dual-rate shaping (PIR / CIR / CBS). Optional on top of bandwidth_bps.
	//
	//	bandwidth_bps          PIR — peak rate, what a burst is allowed to reach
	//	committed_bps          CIR — committed rate, what is sustained forever
	//	committed_burst_bytes  CBS — how much may be spent at PIR before falling
	//	                             back to CIR
	//
	// Leaving committed_bps at 0 keeps the plain single-rate behaviour: one
	// bucket at bandwidth_bps. Setting it stacks a second, much deeper bucket
	// behind the peak one — traffic has to clear both, so a fresh line runs at
	// PIR until its burst allowance drains and then settles at CIR.
	//
	// committed_burst_bytes = 0 means "one day of the committed rate", which is
	// the sane default: a customer may spend their daily commitment whenever
	// they like, at full speed, and still never exceed it over the day.
	// committed_bps above bandwidth_bps is meaningless and is ignored.
	CommittedBps        uint64 `protobuf:"varint,6,opt,name=committed_bps,json=committedBps,proto3" json:"committed_bps,omitempty"`
	CommittedBurstBytes uint64 `protobuf:"varint,7,opt,name=committed_burst_bytes,json=committedBurstBytes,proto3" json:"committed_burst_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_protocol_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_protocol_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_protocol_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAccount() *serial.TypedMessage {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *User) GetBandwidthBps() uint64 {
	if x != nil {
		return x.BandwidthBps
	}
	return 0
}

func (x *User) GetConnLimit() uint32 {
	if x != nil {
		return x.ConnLimit
	}
	return 0
}

func (x *User) GetCommittedBps() uint64 {
	if x != nil {
		return x.CommittedBps
	}
	return 0
}

func (x *User) GetCommittedBurstBytes() uint64 {
	if x != nil {
		return x.CommittedBurstBytes
	}
	return 0
}

var File_common_protocol_user_proto protoreflect.FileDescriptor

const file_common_protocol_user_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/protocol/user.proto\x12\x14xray.common.protocol\x1a!common/serial/typed_message.proto\"\x8b\x02\n" +
	"\x04User\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12:\n" +
	"\aaccount\x18\x03 \x01(\v2 .xray.common.serial.TypedMessageR\aaccount\x12#\n" +
	"\rbandwidth_bps\x18\x04 \x01(\x04R\fbandwidthBps\x12\x1d\n" +
	"\n" +
	"conn_limit\x18\x05 \x01(\rR\tconnLimit\x12#\n" +
	"\rcommitted_bps\x18\x06 \x01(\x04R\fcommittedBps\x122\n" +
	"\x15committed_burst_bytes\x18\a \x01(\x04R\x13committedBurstBytesB^\n" +
	"\x18com.xray.common.protocolP\x01Z)github.com/xtls/xray-core/common/protocol\xaa\x02\x14Xray.Common.Protocolb\x06proto3"

var (
	file_common_protocol_user_proto_rawDescOnce sync.Once
	file_common_protocol_user_proto_rawDescData []byte
)

func file_common_protocol_user_proto_rawDescGZIP() []byte {
	file_common_protocol_user_proto_rawDescOnce.Do(func() {
		file_common_protocol_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_protocol_user_proto_rawDesc), len(file_common_protocol_user_proto_rawDesc)))
	})
	return file_common_protocol_user_proto_rawDescData
}

var file_common_protocol_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_protocol_user_proto_goTypes = []any{
	(*User)(nil),                // 0: xray.common.protocol.User
	(*serial.TypedMessage)(nil), // 1: xray.common.serial.TypedMessage
}
var file_common_protocol_user_proto_depIdxs = []int32{
	1, // 0: xray.common.protocol.User.account:type_name -> xray.common.serial.TypedMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_protocol_user_proto_init() }
func file_common_protocol_user_proto_init() {
	if File_common_protocol_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_protocol_user_proto_rawDesc), len(file_common_protocol_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_protocol_user_proto_goTypes,
		DependencyIndexes: file_common_protocol_user_proto_depIdxs,
		MessageInfos:      file_common_protocol_user_proto_msgTypes,
	}.Build()
	File_common_protocol_user_proto = out.File
	file_common_protocol_user_proto_goTypes = nil
	file_common_protocol_user_proto_depIdxs = nil
}
